name: sphinx_verify
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  crypto: ^3.0.6
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  intl: ^0.19.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
