name: sphinx_verify
description: Sphinx Verify is a Flutter package that amis to provider a interface to amazon recognition service. with built-in use cases.
homepage: https://github.com/moesaid/SphinxVerify
repository: https://github.com/moesaid/SphinxVerify
version: 1.0.2
screenshots:
  - description: "Sphinx Verify is a Flutter package that amis to provider a interface to amazon recognition service. with built-in use cases."
    path: marketing/logo.png
topics:
  - amazon-rekognition
  - face-detection
  - text-detection
  - compare-faces
  - content-moderation

environment:
  sdk: ^3.5.0
  flutter: '>=3.24.0'

dependencies:
  crypto: ^3.0.6
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ">=6.0.0 <8.0.0"

flutter:
  assets:
    - packages/sphinx_verify/assets/images/kyc.png
    - packages/sphinx_verify/assets/images/face-id.png
    - packages/sphinx_verify/assets/images/id-card.png